name: Exchequer
main: name.richardson.james.bukkit.exchequer.Exchequer
description: ${project.description}
version: 0.0.1-SNAPSHOT
database: true
commands:
  ex:
    description: 'Additional exchequer commands'

